doctrine:
  dbal:
    default_connection: pgsql
    url: url: '%env(DATABASE_URL)%'
    charset: utf8
    connections:
      # Postgresl
      pgsql:
        driver: pdo_pgsql
        host:     localhost
        port:     5432
        dbname:   db
        user:     postgres
        password: '34Zc18WfLn'
        charset: utf8
        server_version: '10.5'

  orm:
    auto_generate_proxy_classes: "%kernel.debug%"
    naming_strategy: doctrine.orm.naming_strategy.underscore
    auto_mapping: true
    entity_managers:
      pgsql:
        connection: db
        mappings: